######################################################
# Global attributes
data_folder: 
    scinet: ./data/
    default: ./data/

tmp_folder: tmp/

# The initial number of random points to download
# and mark as training
random_point_count: 2000
percent_training: 0.6


# Years of daymet data to download
daymet_years_start: 1995
daymet_years_end: 2018

ndvi_years_start: 2001
ndvi_years_end:   2019

# MODIS NDVI Filtering scheme. 
# Only keep pixels with at least this many dates/year in 19 years
ndvi_minimum_dates_per_year: 10
ndvi_minimum_years_with_x_dates: 19


# Model fitting stuff
training_year_sets:
    - start: 2001
      end: 2009
    - start: 2010
      end: 2018

full_model_predictions_file: full_model_predictions.csv
